apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "charts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --keycloak-url={{ .Values.keycloak.url }}
            - --interval={{ .Values.interval }}
            - --keycloak-realm={{ .Values.keycloak.realm }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if or .Values.keycloak.auth.username .Values.keycloak.auth.usernameSecret }}
            - name: KEYCLOAK_USER
              {{- if .Values.keycloak.auth.username }}
              value: {{ .Values.keycloak.auth.username }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.keycloak.auth.usernameSecret | nindent 18 }}
              {{- end }}
            {{- end }}
            {{- if or .Values.keycloak.auth.username .Values.keycloak.auth.passwordSecret }}
            - name: KEYCLOAK_PASSWORD
              {{- if .Values.keycloak.auth.password }}
              value: {{ .Values.keycloak.auth.password }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.keycloak.auth.passwordSecret | nindent 18 }}
              {{- end }}
            {{- end }}
            {{- if or .Values.slack.url .Values.slack.urlSecret }}
            - name: SLACK_URL
              {{- if .Values.slack.url }}
              value: {{ .Values.slack.url }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.slack.urlSecret | nindent 18 }}
              {{- end }}
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
